# Checkout repo and run tests for python versions >= 3.6
name: CI
on:
  push:
  release:
    types:
      - release
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
    name: python-${{ matrix.python-version }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install python-${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y imagemagick
          python${{ matrix.python-version }} -m pip install rgb565-converter
      
      - name: Prepare Tests
        run: |
          mkdir -p /tmp/tests
          ls -lah 
          cp -r tests/* /tmp/tests
          cd /tmp/tests
          mkdir -p /tmp/tests/output
      
      - name: Perform Tests
        run: |
          rgb565-converter -i /tmp/tests/input/info.png -o /tmp/tests/output/info.cpp
          rgb565-converter -i /tmp/tests/input/info.cpp -o /tmp/tests/output/info.png
          cat /tmp/tests/input/info.cpp
          cat /tmp/tests/output/info.cpp